name: Crash report
description: Submit a crash report to help us improve.
labels: [ 'bug', 'critical' ]

body:
  - type: textarea
    attributes:
      label: Environment
      description: |
        What platform and version of Java are you using?

        Example:
          - **Operating System**: Debian 11
          - **Java**: Eclipse Temurin 17.0.1
      value: |
        - **Operating System**:
        - **Java**:
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash logs
      description: |
        The crash report, or the logs leading up to the crash.

        Tip: You can click the text box then drag the files into here in place of the details tags.
      value: |
        <details><summary>Latest logs</summary><code>

        <!-- Paste the log here. Be sure to omit any sensitive information such as any passwords. -->

        </code></details>
        <details><summary>Crash Report</summary><code>

        <!-- Paste the crash report here. Be sure to omit any sensitive information such as any passwords. -->

        </code></details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Any additional logs, screenshots and videos should go here.
    validations:
      required: false