name: Feature request
description: Suggest an idea for maven.sock.
labels: [ 'enhancement' ]

body:
  - type: textarea
    attributes:
      label: What would you like to be added?
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context?
    validations:
      required: false